### ISSUE TITLE
代码主题问题

### ISSUE THREAD

**Issue by ghost** [wangyang0210/EasyBe#4]
为什么从首页进入文章和分类进入文章还有档案进入文章，文章代码格式不一样，还是在哪设置呢？

首页进入
![image](https://user-images.githubusercontent.com/48847838/70222860-97050800-1785-11ea-9182-102d928809ae.png)

分类进入
![image](https://user-images.githubusercontent.com/48847838/70222922-b00db900-1785-11ea-930b-65adb1c7eac8.png)

档案进入
![image](https://user-images.githubusercontent.com/48847838/70222952-b865f400-1785-11ea-84fd-1cb59827115b.png)

**Comment by wangyang0210** [comment]
这个是因为当时搞一半了，然后之前公司比较忙，一直忙着公司的事情了，这个后面会修复掉

**Comment by wangyang0210** [comment]
已修复
