### ISSUE TITLE
终于更新了！！！！！！

### ISSUE THREAD

**Issue by lingnan888** [wangyang0210/EasyBe#8]
终于更新了！！！！！！终于更新了！！！！！！终于更新了！！！！！！终于更新了！！！！！！终于更新了！！！！！！终于更新了！！！！！！终于更新了！！！！！！终于更新了！！！！！！终于更新了！！！！！！

**Comment by lingnan888** [comment]
用了一下好像还是白屏

**Comment by wangyang0210** [comment]
之前公司有点忙，最近离职了，重新搞了下，现在不会白屏了

**Comment by beauslime** [comment]
您选择的网络风格不存在，求解
